[package]
name = "score2svg"
version = "0.1.0"
authors = ["Jeron Aldaron Lau <jeronlau@plopgrizzly.com>", "Douglas Lau <doug.p.lau@gmail.com>"]
edition = "2018"

[dependencies]
scof = { path = "../scof" }
svg = "0.5"